# Generated by Django 5.0.7 on 2024-08-12 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
