# Generated by Django 5.0.7 on 2024-08-13 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator('Enter a valid email address.')]),
        ),
    ]
