# Generated by Django 5.0.7 on 2024-08-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
    ]
